name: Deploy
on:
  push:
    branches: [main]

jobs:

  display:
    runs-on: ubuntu-latest
    steps:
      - name: Print a value
        run: echo Hello from first job 

  deploy:
    runs-on: ubuntu-latest
    needs: display
    if: always()
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Cloud Foundry
        uses: jhunt/cf-push@v1
        with:
          api:      ${{ secrets.CF_API }}
          org:      ${{ secrets.CF_ORG }}
          space:    ${{ secrets.CF_SPACE }}
          username: ${{ secrets.CF_USERNAME }}
          password: ${{ secrets.CF_PASSWORD }}
          manifest: manifest.yml
          validate: false
