name: Deploy
on:
  push:
    branches: [main]

jobs:

  display:
    runs-on: ubuntu-latest
    steps:
      - name: Print a value
        run: echo Hello from first job 

  deploy:
    runs-on: ubuntu-latest
    needs: display
    if: always()
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Cloud Foundry
        uses: jhunt/cf-push@v1
        with:
          api:      ${{ secrets.CF_API }}
          org:      ${{ secrets.CF_ORG }}
          space:    ${{ secrets.CF_SPACE }}
          username: ${{ secrets.CF_USERNAME }}
          password: ${{ secrets.CF_PASSWORD }}
          manifest: manifest.yml
          validate: false

  success-notification:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v2
      - run: exit 0
      - name: Slack Success
        if: always()
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_WEBHOOK }}
          channel: ${{ secrets.SLACK_CHANNEL }}

  failure-notification:
    runs-on: ubuntu-latest
    needs: success-notification
    steps:
      - uses: actions/checkout@v2
      - run: exit 1
      - name: Slack Failure
        if: always()
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_WEBHOOK }}
          channel: ${{ secrets.SLACK_CHANNEL }}
